language: node_js
cache: yarn
node_js:
  - "12"
  - "10"
  - "8"

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: yarn test:coverage
